// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $index from "./routes/index.tsx";
import * as $users from "./routes/users.tsx";
import * as $TaskBoard from "./islands/TaskBoard.tsx";
import * as $TaskForm from "./islands/TaskForm.tsx";
import * as $UserForm from "./islands/UserForm.tsx";
import * as $UserManagement from "./islands/UserManagement.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/index.tsx": $index,
    "./routes/users.tsx": $users,
  },
  islands: {
    "./islands/TaskBoard.tsx": $TaskBoard,
    "./islands/TaskForm.tsx": $TaskForm,
    "./islands/UserForm.tsx": $UserForm,
    "./islands/UserManagement.tsx": $UserManagement,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
